# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.14.4 is version 28
    loaderVersion="[31,)"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false

    [[mods]]
      modId="hello"
      version="1.0.0"
      displayName="Hello Mod"
      logoFile="logo.png"
      authors="Yang Le"
      description='''
      This is a hello world example for minecraft mod.'''

      [[dependencies.hello]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.hello]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"
